image: node:latest

before_script:
  - apt-get -qq update
  - apt-get install -y jq
  - npm install get-json
  - npm install shelljs
  - npm install surge

main:
  stage: deploy
  variables:
    API_KEY: $API_KEY
    DOMAIN_KEY: $DOMAIN_KEY
    FROM_KEY: $FROM_KEY
    TO_KEY: $TO_KEY
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - node node_script.js schedule
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - node node_script.js web